import type { BookDetail } from "../screens/KoreanPage/BookDetailDrawer";

// Google Books cover helper (ISBN -> cover img)
const coverByIsbn = (isbn: string) =>
  `https://books.google.com/books/content?vid=ISBN:${isbn}&printsec=frontcover&img=1&zoom=1`;
// Google Books preview page
const gbooks = (isbn: string) => `https://books.google.com/books?vid=ISBN:${isbn}`;

// Rasmiy resurslar (MP3/Video/QR) – Two Ponds
const SNU_RESOURCES = "https://www.twoponds.co.kr/en/snu";

export const BOOKS: BookDetail[] = [
  {
    id: "snu-1a",
    title: "SNU Korean 1A (o‘quvchi kitobi)",
    authors: ["SNU LEI"],
    rating: 4.8,
    ratingCount: 23122,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131171"),
    price: 23, oldPrice: 28, discountPct: 18,
    overview: "Korean, asosiy grammatika va kundalik nutqning birinchi bosqichi.",
    learnBullets: ["Korean o‘qish/yozish", "Batchim talaffuz", "은/는/이/가 ko‘makchilari", "Hozirgi zamon -아요/어요"],
    includes: ["Audio/QR resurslar", "Ish daftari (alohida)", "Kultura eslatmalari"],
    attachments: [
      { id: "buy", name: "Buy (UBookstore) – ISBN 9788952131171", kind: "link", url: "https://online.fliphtml5.com/xihiu/mtft/#p=1" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952131171") },
    ],
  },
  {
    id: "snu-1b",
    title: "SNU Korean 1B (o‘quvchi kitobi)",
    authors: ["SNU LEI"],
    rating: 4.8,
    ratingCount: 19840,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131188"),
    price: 23, oldPrice: 28, discountPct: 18,
    overview: "1A davomchisi: kundalik vaziyatlar, savol-javob, fe’l zamonlari.",
    learnBullets: ["Fe’llar zamoni kengaytmasi", "Gap tuzilishi", "Asosiy so‘z boyligi"],
    includes: ["Audio/QR resurslar", "Mashq daftar", "Javoblar bo‘limi"],
    attachments: [
      { id: "buy", name: "Buy (Amazon) – ISBN 9788952131188", kind: "link", url: "https://www.scribd.com/document/513064721/%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-Student-s-Book-1B" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952131188") },
    ],
  },
  {
    id: "snu-2a",
    title: "SNU Korean 2A (o‘quvchi kitobi)",
    authors: ["SNU LEI"],
    rating: 4.7,
    ratingCount: 17510,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131232"),
    price: 25, oldPrice: 29, discountPct: 14,
    overview: "Sifat/ravishlar, shart mayli va iltimos/taklif ifodalari.",
    learnBullets: ["Shart mayli ~(으)면", "Taklif/iltimos", "Suhbatlarni kengaytirish"],
    includes: ["Audio/QR", "Grammar supplement", "Glossariy"],
    attachments: [
      { id: "buy", name: "Buy (koreanbook.de) – ISBN 9788952131232", kind: "link", url: "https://www.scribd.com/document/675200850/%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-SNU-Korean-2A-Student-s-Book-2" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952131232") },
    ],
  },
  {
    id: "snu-2b",
    title: "SNU Korean 2B (o‘quvchi kitobi)",
    authors: ["SNU LEI"],
    rating: 4.7,
    ratingCount: 16200,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131249"),
    price: 25, oldPrice: 29, discountPct: 14,
    overview: "Sabab-oqibat bog‘lovchilar va kundalik mavzularda uzoqroq dialoglar.",
    learnBullets: ["-아서/어서", "-아/어 보다", "-려고 하다"],
    includes: ["Audio/QR", "Ish daftari (alohida)", "Madaniyat bo‘limi"],
    attachments: [
      { id: "buy", name: "Buy (Amazon) – ISBN 9788952131249", kind: "link", url: "https://www.scribd.com/document/623136555/%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-SNU-Korean-2B-Student-s-Book" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952131249") },
    ],
  },
  {
    id: "snu-3a",
    title: "SNU Korean 3A (o‘rta daraja)",
    authors: ["SNU LEI"],
    rating: 4.7,
    ratingCount: 14110,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131553"),
    price: 27, oldPrice: 32, discountPct: 16,
    overview: "Murakkab gaplar, rasmiy/uslubiy nutq, mavzuli matnlar.",
    learnBullets: ["Qo‘shimcha bog‘lovchilar", "Passiv/Kausativ kirish", "Nutq registrlari"],
    includes: ["Audio/QR", "Grammar supplement", "Javoblar"],
    attachments: [
      { id: "buy", name: "Buy (UBookstore) – ISBN 9788952131553", kind: "link", url: "https://www.scribd.com/document/623135099/%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-SNU-Korean-3A-Student-s-Book" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952131553") },
    ],
  },
  {
    id: "snu-3b",
    title: "SNU Korean 3B (o‘rta daraja)",
    authors: ["SNU LEI"],
    rating: 4.7,
    ratingCount: 13340,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131560"),
    price: 27, oldPrice: 32, discountPct: 16,
    overview: "Fe’l yasovchi qo‘shimchalar, ko‘makchi fe’llar, uzun matnlar.",
    learnBullets: ["~게 되다 / ~게 하다", "-아/어 놓다, -아/어 두다", "Murakkab bog‘lovchilar"],
    includes: ["Audio/QR", "Workbook (alohida)", "Madaniyat bo‘limi"],
    attachments: [
      { id: "buy", name: "Buy (UBookstore) – ISBN 9788952131560", kind: "link", url: "https://www.scribd.com/document/623136667/%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-SNU-Korean-3B-Student-s-Book" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952131560") },
    ],
  },
  {
    id: "snu-4a",
    title: "SNU Korean 4A (yuqori o‘rta)",
    authors: ["SNU LEI"],
    rating: 4.8,
    ratingCount: 12020,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952131775"), // Plus versiya
    price: 29, oldPrice: 35, discountPct: 17,
    overview: "Insho/taqdimot, stilistika, uzoq akademik matnlar.",
    learnBullets: ["Rasmiy uslub", "Qiyos/xulosa/dalillash", "Frazeologizmlar"],
    includes: ["Audio/QR", "Practice units", "Glossariy"],
    attachments: [
      { id: "buy", name: "Buy (AprendeCoreanoHoy) – ISBN 9788952131775", kind: "link", url: "https://www.scribd.com/document/577716949/Seoul-University-Korean-%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-4A-Student-s-book" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview (old ver. 4A)", kind: "link", url: gbooks("9788953948822") },
    ],
  },
  {
    id: "snu-4b",
    title: "SNU Korean 4B (yuqori o‘rta)",
    authors: ["SNU LEI"],
    rating: 4.8,
    ratingCount: 11330,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788953948839"),
    price: 29, oldPrice: 35, discountPct: 17,
    overview: "Akademik matnlar, murakkab sintaksis va registr.",
    learnBullets: ["Qo‘shma gaplar", "Pragmatik bo‘yoq", "Nutq etiketi"],
    includes: ["Audio/QR", "Workbook (alohida)", "Yozma topshiriqlar"],
    attachments: [
      { id: "buy", name: "Buy (Amazon – +4B)", kind: "link", url: "https://www.scribd.com/document/717717727/SNU-4B-new" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview – 4B", kind: "link", url: gbooks("9788953948839") },
    ],
  },
  {
    id: "snu-5a",
    title: "SNU Korean 5A (yuqori)",
    authors: ["SNU LEI"],
    rating: 4.9,
    ratingCount: 10115,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788953949607"),
    price: 32, oldPrice: 39, discountPct: 18,
    overview: "Munozara, eslatma va ma’ruza tili, abstrakt mavzular.",
    learnBullets: ["Murakkab so‘z yasalishi", "Rasmiy yozishmalar", "Nutq strategiyalari"],
    includes: ["Audio/QR", "Yakuniy review bo‘limlari", "Glossariy"],
    attachments: [
      { id: "buy", name: "Buy (AprendeCoreanoHoy) – ISBN 9788953949607", kind: "link", url: "https://www.scribd.com/document/873382751/%EC%84%9C%EC%9A%B8%EB%8C%80-%ED%95%9C%EA%B5%AD%EC%96%B4-5" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788953949607") },
    ],
  },
  {
    id: "snu-5b",
    title: "SNU Korean 5B (yuqori)",
    authors: ["SNU LEI"],
    rating: 4.9,
    ratingCount: 9640,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952132017"),
    price: 32, oldPrice: 39, discountPct: 18,
    overview: "Matn tahlili, stilistika, pragmatika — professional kontekstlar.",
    learnBullets: ["Nutq uslublari", "Metafora/idiomalar", "Dalillash strukturalari"],
    includes: ["Audio/QR", "Workbook (alohida)", "Writing tasks"],
    attachments: [
      { id: "buy", name: "Buy (AprendeCoreanoHoy) – ISBN 9788952132017", kind: "link", url: "https://www.scribd.com/document/839147309/SNU-Korean-5B-Workbook" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788952132017") },
    ],
  },
  {
    id: "snu-6a",
    title: "SNU Korean 6A (eng yuqori)",
    authors: ["SNU LEI"],
    rating: 4.9,
    ratingCount: 8815,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788952132079"), // +6A (2023)
    price: 35, oldPrice: 42, discountPct: 17,
    overview: "Professional/ilmiy mavzular: yozma va og‘zaki taqdimotlar.",
    learnBullets: ["Annotatsiya/xulosa", "Terminologiya", "Rasmiy nutq protokoli"],
    includes: ["Audio/QR", "Advanced reading/listening", "Presentation tasks"],
    attachments: [
      { id: "buy", name: "Buy (koreanbook.de) – ISBN 9788952132079", kind: "link", url: "https://www.scribd.com/document/748298746/49436-50872-45824-54620-44397-50612-SNU-Korean-6A-Workbook" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview (old ver. 6A)", kind: "link", url: gbooks("9788953949645") },
    ],
  },
  {
    id: "snu-6b",
    title: "SNU Korean 6B (eng yuqori)",
    authors: ["SNU LEI"],
    rating: 4.9,
    ratingCount: 8420,
    pairLang: "KO → UZ",
    cover: coverByIsbn("9788953949652"),
    price: 35, oldPrice: 42, discountPct: 17,
    overview: "Konseptual matnlar, debat va akademik yozuvlar.",
    learnBullets: ["Debat strukturasi", "Kengaytirilgan sintaksis", "Akademik yozuv normasi"],
    includes: ["Audio/QR", "Workbook (alohida)", "Assessment topshiriqlar"],
    attachments: [
      { id: "buy", name: "Buy (Amazon) – ISBN 9788953949652", kind: "link", url: "https://www.scribd.com/document/648111348/49436-50872-45824-54620-44397-50612-SNU-Korean-6B-Student-s-Book" },
      { id: "resources", name: "Official resources (MP3/Video/QR)", kind: "link", url: SNU_RESOURCES },
      { id: "preview", name: "Google Books preview", kind: "link", url: gbooks("9788953949652") },
    ],
  },
];
